version: '3'
services:
  app-client:
    image: jzywiecki/devx-app-client:latest
    container_name: "client"
    restart: always
    env_file: ".env"
    ports:
      - "5173:5173"

  app-server:
    image: jzywiecki/devx-app-server:latest
    container_name: "server"
    restart: always
    env_file: ".env"

  app-auth-service:
    image: jzywiecki/devx-app-auth-service:latest
    container_name: "auth-service"
    restart: always
    env_file: ".env"
    ports:
      - "3333:3333"

  app-realtime-server:
    image: jzywiecki/devx-app-realtime-server:latest
    container_name: "realtime-server"
    restart: always
    env_file: ".env"
