version: '3'
services:
  app-client:
    platform: linux/amd64
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "client"
    restart: always
    ports:
      - "5173:5173"

  app-server:
    platform: linux/amd64
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "server"
    restart: always
    env_file: ".env"
        ports:
      - "8000:8000"

  app-auth-service:
    platform: linux/amd64
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: "auth-service"
    restart: always
    env_file: ".env"
    ports:
      - "3333:3333"

  app-realtime-server:
    platform: linux/amd64
    build:
      context: ./realtime-server
      dockerfile: Dockerfile
    container_name: "realtime-server"
    restart: always
    env_file: ".env"
    ports:
      - "3000:3000"


